language: php

php:
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --dev

script:
    - mkdir -p build/logs
    - make sniff test

after_script:
    - php vendor/bin/coveralls -v
